# Generated by Django 3.0.7 on 2020-06-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_auto_20200625_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coverpic',
            field=models.ImageField(blank=True, upload_to='coverpics'),
        ),
    ]
